"use client";

import { cn } from "@/lib/utils/cn";

type AIBadgeProps = {
  /** Show just the icon (compact) or icon + "AI" text */
  variant?: "full" | "icon";
  size?: "sm" | "md";
  className?: string;
};

/**
 * Purple sparkle badge indicating AI-generated content.
 * Per spec §1: all AI content must be visually distinguishable.
 */
export function AIBadge({ variant = "full", size = "sm", className }: AIBadgeProps) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full font-semibold text-ai",
        size === "sm" ? "text-2xs" : "text-xs",
        variant === "full" && "bg-ai-muted px-2 py-0.5",
        className
      )}
      title="This content was generated by AI analysis of your data"
    >
      <SparkleIcon className={size === "sm" ? "h-3 w-3" : "h-3.5 w-3.5"} />
      {variant === "full" && <span>AI</span>}
    </span>
  );
}

function SparkleIcon({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 16 16"
      fill="currentColor"
      className={className}
      aria-hidden="true"
    >
      <path d="M8 0a.5.5 0 0 1 .5.5v2.036a5.5 5.5 0 0 1 4.964 4.964H15.5a.5.5 0 0 1 0 1h-2.036a5.5 5.5 0 0 1-4.964 4.964V15.5a.5.5 0 0 1-1 0v-2.036A5.5 5.5 0 0 1 2.536 8.5H.5a.5.5 0 0 1 0-1h2.036A5.5 5.5 0 0 1 7.5 2.536V.5A.5.5 0 0 1 8 0Zm0 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z" />
      <path d="M3 0a.25.25 0 0 1 .25.25v1a.25.25 0 0 1-.5 0v-1A.25.25 0 0 1 3 0Zm0 2.5a.25.25 0 0 1 .25.25v1a.25.25 0 0 1-.5 0v-1A.25.25 0 0 1 3 2.5ZM1.75 1a.25.25 0 0 1 0 .5h-1a.25.25 0 0 1 0-.5h1Zm2.5 0a.25.25 0 0 1 0 .5h-1a.25.25 0 0 1 0-.5h1Z" />
    </svg>
  );
}

/**
 * Wrapper that adds the AI visual distinction to a section:
 * purple left border + AI badge in the top-right.
 */
export function AIInsightWrapper({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "relative rounded-lg border border-border bg-card p-5 border-l-2 border-l-ai",
        className
      )}
    >
      <div className="absolute right-3 top-3">
        <AIBadge />
      </div>
      {children}
    </div>
  );
}
